# -*- coding: utf-8 -*-
"""veri_önişleme_şablonu_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4k_7SAz_ezTBgBhcTV00iqXtBjxQ9F7

# **1. islem kutuphaneler**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# **2. veri önişleme**

**2.1 verilerin yüklenmesi**
"""

veriler = pd.read_csv("veriler.csv")

"""**test**"""

veriler

x = veriler.iloc[:,1:4].values # bağımsız
y = veriler.iloc[:,4:].values #bağımlı

"""**verilerin eğitim ve test için bölünmesi**"""

from sklearn.model_selection import train_test_split

x_train , x_test ,y_train , y_test = train_test_split(x , y , test_size= 0.33 , random_state = 0)

"""**verilerin ölçeklenmesi**"""

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

"""# ***buradan itibaren sınıflandırma algoritmaları başlar***

***1. Logistic Regression***
"""

from sklearn.linear_model import LogisticRegression

logr = LogisticRegression(random_state=0)

logr.fit(X_train, y_train)

y_pred = logr.predict(X_test)
y_pred

